/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.finalresults;

/**
 *
 * @author Djordje Gligorijevic
 */
public class PnlFinalResultsPreview extends javax.swing.JPanel {

    /**
     * Creates new form PnlFinalResultsPreview
     */
    public PnlFinalResultsPreview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResultsPreview = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResultsPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResultsPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblResultsPreview;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lblResultsPreview
     */
    public javax.swing.JLabel getLblResultsPreview() {
        return lblResultsPreview;
    }

    /**
     * @param lblResultsPreview the lblResultsPreview to set
     */
    public void setLblResultsPreview(javax.swing.JLabel lblResultsPreview) {
        this.lblResultsPreview = lblResultsPreview;
    }
}
